### ISSUE TITLE
Add code quality checks

### ISSUE THREAD

**Issue by cjgrady** [lifemapper/lm_test#18]
**Is your feature request related to a problem? Please describe.**
It is easier to keep the code quality of a code-base high rather than restore it to high quality.

**Describe the solution you'd like**
I would like to add code-quality checks via github actions and / or pre-commit hooks so that we prevent code quality issues from ourselves and others before they are merged.

**Describe alternatives you've considered**
I have tried this through GitHub actions and `super-linter` but @maxxxxxdlp pointed out pre-commit and that seems to be a better way to go about it since the bad code is never even committed.

**Comment by maxxxxxdlp** [comment]
The [GitHub action](https://github.com/pre-commit/action) for pre-commit hook would test entire codebase on any push. This is why it is best to adopt it early in the process, or else it would be hard to convert.

Like [Ben said](https://github.com/specify/specify7/pull/792#issuecomment-821284500), running pre-commit hooks on Specify 7's code base resulted in hundreds of changed files and a zillion error messages.

**Comment by cjgrady** [comment]
Yes, I have noticed that too and would like to integrate it now before it grows too much.  I really have already but want an issue to attach that pull request to.

I see the value in including PyTest tests separate from pre-commit as you may want to commit changes that have not been fully tested or maybe not all of the bugs have been worked out.  Maybe the tests are run whenever a push is attempted?

Do you know if that is possible for pre-commit?  My main concern is that including it on pre-commit hooks will raise the barrier to entry too high for any outside contributors and I would like to avoid that.  It is less important for this repository but vital for the Biotaphy repositories that I want students contributing to.
