### ISSUE TITLE
Add GitHub's CodeQL for security precautions

### ISSUE THREAD

**Issue by cjgrady** [lifemapper/lm_test#20]
**Is your feature request related to a problem? Please describe.**
We need to know if one of the libraries / repositories that we depend on has security vulnerabilities.

**Describe the solution you'd like**
GitHub's CodeQL tool seems to provide this functionality.

**Describe alternatives you've considered**
There may be other tools that do this or could do this even better.  It is worth looking into.

**Additional context**
[CodeQL](https://securitylab.github.com/tools/codeql/)

**Comment by cjgrady** [comment]
@maxpatiiuk you have experience with this so it may be best for you to set it up initially.  I'd like to look into it too though.

**Comment by maxxxxxdlp** [comment]
Added in 71eaa3e9f175bac74f9681f718250af42c3594b0

**Comment by maxxxxxdlp** [comment]
@cjgrady It seems to fail because the `requirements.txt` file points to a nonexisting repository github.com/lifemapper/ot_service_wrapper

**Comment by cjgrady** [comment]
Cool, I filed #34 to address this.  #30 may also resolve this if we remove that particular test class.

**Comment by cjgrady** [comment]
I fixed #34 and now the action passes.  Closing this issue.
